undone:


4.3 load model error
yolo_model = load_model("model_data/yolo.h5")